name: Deploy datasette

on:
  push:
    branches:
    - master
  workflow_dispatch:
  schedule:
    - cron: '15 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Build SQLite database
      run: |
        curl -s https://cloud.minsa.gob.pe/s/ZgXoXqK2KLjRLxD/download | \
          sqlite-utils insert vacunas_covid.db vacunas_covid - --pk UUID --pk DOSIS --csv
        sqlite-utils create-view vacunas_covid.db vacunados_por_dia \
          "select FECHA_VACUNACION, count(*) as TOTAL_VACUNADOS \
           from vacunas_covid \
           group by FECHA_VACUNACION \
           order by FECHA_VACUNACION DESC"
    - name: Deploy datasette to heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |-
        npm install -g heroku
        heroku plugins:install heroku-builds
        datasette publish heroku vacunas_covid.db \
          --metadata metadata.json \
          --name vacunas-covid-peru \
          --install datasette-vega \
          --extra-options "--setting sql_time_limit_ms 3000"
