name: Flat

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://cloud.minsa.gob.pe/s/ZgXoXqK2KLjRLxD/download
          downloaded_filename: ./data/registro_vacunacion.csv
      - name: Check python version
        run: |
          which python
          python --version

